### ISSUE TITLE
Support Inklecate path configuration for multiple developers

### ISSUE THREAD

**Issue by BenjaminLawson** [paulloz/godot-ink#35]
Currently, the `inklecate` settings path is shared by all developers for the same project. This is not viable because different developers have different paths to their `inklecate` binary.

Inkgd solves this by writing the binary paths to a config file that can be kept out of version control: https://github.com/ephread/inkgd#editor

**Comment by BenjaminLawson** [comment]
If `OS.execute` supported relative or `res://` paths this could also be solved by putting inklecate right in the project directory.

**Comment by paulloz** [comment]
Hey @BenjaminLawson, sorry I did not answer earlier.  
I'm still thinking about what would be the best viable solution for this, this is a pretty big and important issue. I don't really like the idea of not using the proper Godot settings and making a separate configuration file though.  
At the moment, I pushed a workaround in acea307. Like you suggested in your last comment, the setting is now relative to `res://` so everything should at least be *usable*. I'm not a fan of not permitting to have inklecate outside the project's folder but it'll do for now.

**Comment by francoisdlt** [comment]
We have the same issue on our project, and since we have developers using Mac and Windows, this solution helps a little but does not solve all problems (since the inklecate binary is not the same for windows and mac)

I think i'll fork the plugin and have two distinct inklecate path properties : "inklecate-mac" and "inklecate-windows", both relative to `res://` so we can version them and avoid conflicts.

**Comment by paulloz** [comment]
Humpf, I didn’t think about that either (seems like I don’t think much these days). 
If you want to open a PR with what you’re suggesting I’m open to merging it. I feels it is a decent temporary solution while I (or more probably someone else) come up with a really good way of handling this.

**Comment by paulloz** [comment]
As of dde8c313c181836f9c3f1e2585052804cfd5bead, the setting can be overridden from a file that can be excluded from VCS. This will be available in `0.10`.
